### PR TITLE
Implement stubdom variants: minimal and full (audio and usb support)

### PR DESCRIPTION
**Pull request by easydozen**
QubesOS/qubes-issues#5802

### CODE REVIEW

**Comment by easydozen** [comment]
At the moment this PR doesn't contain changes to the specification. I'm in doubt how it would be better to support stubdom variants: both in one package, two packages in one specification or split them into two specifications.

**Comment by marmarek** [comment]
Definitely one spec file - while theoretically we do support multiple spec files in one repository, we are phasing this out.
As for whether one or two packages, I don't have any strong opinion, but I'm leaning towards two.

See the build log, I think you forgot to update kernel version in some file.
I haven't reviewed the actual changes yet.

**Comment by easydozen** [comment]
I'm waiting here for QubesOS/qubes-core-qrexec/pull/66 resolution.

**Comment by marmarek** [comment]
Thanks for pushing update to the other PR. I feel like I need to explain why I haven't merged this all yet, although most looks good. I don't want to introduce any more changes to the picture (Xen, stubdom, qemu etc) before finding the cause of https://github.com/QubesOS/qubes-issues/issues/6174. It is a serious regression and changing more pieces won't make it easier to debug. Sadly, I don't have any conclusive results yet, but I can tentatively say it isn't caused by the qemu update that happen in the meantime too.
Maybe, by a chance, you have some ideas?

**Comment by easydozen** [comment]
> Thanks for pushing update to the other PR. I feel like I need to explain why I haven't merged this all yet, although most looks good. I don't want to introduce any more changes to the picture (Xen, stubdom, qemu etc) before finding the cause of [QubesOS/qubes-issues#6174](https://github.com/QubesOS/qubes-issues/issues/6174). It is a serious regression and changing more pieces won't make it easier to debug. Sadly, I don't have any conclusive results yet, but I can tentatively say it isn't caused by the qemu update that happen in the meantime too.
> Maybe, by a chance, you have some ideas?

I haven't spotted such regression. 
I'll definitely look closer and try to help with this issue.

**Comment by marmarek** [comment]
To be clear, I don't think it is caused by this PR - the issue affects systems without this change too. But adding more changes may make it even harder to debug.

**Comment by marmarek** [comment]
PipelineRetry

**Comment by jevank** [comment]
I guess  this [commit](https://github.com/QubesOS/qubes-app-linux-usb-proxy/pull/22/commits/368bee27d7b19ceed1d14535c77ed66a2752fa9f) to usbproxy required to build working version

**Review by marmarek — APPROVED** [review]

**Pull request merged**
