### PR TITLE
Update qemu to 4.2.0

### PR DESCRIPTION
**Pull request by marmarek**
Remaining issues:
- [x] Qemu fails to start with `qemu: Initialization of device ide-hd failed: Failed to lock byte 100` (The actual syscall is `fcntl(42, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=100, l_len=1}) = -1 EACCES (Permission denied)`, where 42 is `/dev/xvda` open in `O_RDWR` mode)
- [x] A long wait on `getrandom()` syscall.

### CODE REVIEW

**Comment by marmarek** [comment]
This doesn't work for me. There are two issues:
1. Qemu fails to start with `qemu: Initialization of device ide-hd failed: Failed to lock byte 100` (The actual syscall is `fcntl(42, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=100, l_len=1}) = -1 EACCES (Permission denied)`, where 42 is `/dev/xvda` open in `O_RDWR` mode)
2. A long wait on `getrandom()` syscall.

**Comment by jandryuk** [comment]
For getrandom(), you can CONFIG_RANDOM_TRUST_CPU. Or if the kernel is new enough, there is a patch using the scheduler to sees the randomization. https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=50ee7529ec45
That isn't in 5.4.x though

**Comment by marmarek** [comment]
> For getrandom(), you can CONFIG_RANDOM_TRUST_CPU.

This doesn't help that much. I still have about 3s wait. Quick grep says it is used only for VNC which we don't use - I'll try to patch out that call.

**Comment by jandryuk** [comment]
Did you test on real hardware, or in QEMU?  CONFIG_RANDOM_TRUST_CPU should make getrandom() non-blocking, but I think you need RDRAND accessible for the kernel make it non-blocking.

I was wrong about: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=50ee7529ec45
It is in 5.4.y.  I think that is why you see a 3s delay.  On 4.19 without it, the delay exceeded our 10s stubdom startup timeout.

A simpler patch is to change https://github.com/qemu/qemu/blob/f2465433b43fb87766d79f42191607dac4aed5b4/crypto/random-platform.c#L48 and https://github.com/qemu/qemu/blob/f2465433b43fb87766d79f42191607dac4aed5b4/crypto/random-platform.c#L81
to add GRND_NONBLOCK.  Or undefine CONFIG_GETRANDOM.  But like you wrote, the stubdom qemu doesn't need random numbers and your patch is more upstreamable.

**Comment by marmarek** [comment]
I tested on quite old hardware (Intel Core 2nd gen), maybe that's the reason?
Anyway, the patch fixes the issue and I already send it to qemu-devel.

**Comment by jandryuk** [comment]
On Wed, May 20, 2020, 10:21 AM Marek Marczykowski-Górecki <
notifications@github.com> wrote:

> I tested on quite old hardware (Intel Core 2nd gen), maybe that's the
> reason?
>
Wikipedia tells me RDRAND was introduced in 3rd gen.

> Anyway, the patch fixes the issue and I already send it to qemu-devel.
>
Nice.

>

**Pull request merged**
