### PR TITLE
Additional hardening options for kernel and qemu

### PR DESCRIPTION
**Pull request by alcreator**
This PR adds hardening and optimization options for the stubdom kernel, mostly based on configs from qubes-linux-kernel. Seccomp support and additional compile time hardening options for qemu are also included.

Summary:
Kernel:
-Update to version 4.14.18
-Imported xsa155 patches from qubes-linux-kernel
-Enable hardening options based on qubes-linux-kernel configs

Qemu:
-Update to version 2.11.1
-Enable pie (aslr)
-Enable seccomp
-Add additional linker hardening flags
-Disable option rom for e1000 emulated adapter

### CODE REVIEW

**Comment by marmarek** [comment]
GCC mess (almost) sorted out. Now Travis-CI complains about actual issue - missing build dependency (something new in updated qemu? effect of enabling options?).

**Comment by alcreator** [comment]
According to the dnf logs in my build chroot, the pixman/pixman-devel package was downloaded by xen.spec when building the core vmm-xen package. The extra dependency is probably from the updated qemu version. I'll setup a clean chroot instance a little later and check if there are any other missing dependencies.

**Comment by marmarek** [comment]
> According to the dnf logs in my build chroot, the pixman/pixman-devel package was downloaded by xen.spec when building the core vmm-xen package.

But this is not vmm-xen package...

**Comment by alcreator** [comment]
I've updated the PR to include the missing dependency, and to also require the new gcc with retpoline support.

> But this is not vmm-xen package...

What I meant was that I previously compiled vmm-xen with qubes-builder, and it does not clean the chroot when compiling other packages (maybe due to me compiling each package individually?), so I didn't notice the missing dependency.

**Comment by marmarek** [comment]
@HW42

**Comment by alcreator** [comment]
Also, I'm not sure whether it's worth adding retpoline compiler flags to qemu, the theory being that it helps reinforce ASLR for qemu.

**Pull request merged**
