### PR TITLE
IGD passthrough fixes

### PR DESCRIPTION
**Pull request by cytadela8**
Qemu part of @gorbak25 IGD passtrhough fixes

Xen part: https://github.com/QubesOS/qubes-vmm-xen/pull/79

### CODE REVIEW

**Comment by cytadela8** [comment]
POL: ^ podobno to jakiś zły zestaw commitów grzegorza :P
ENG: This is not the correct set of patches. https://github.com/QubesOS/qubes-vmm-xen-stubdom-linux/pull/29 replaces this PR.

**Comment by fepitre** [comment]
@cytadela8: please write in English for everybody can understand what you are saying.

**Comment by marmarek** [comment]
@cytadela8 note I'm close to merging #26, if you foresee any conflicts, please prepare commits on top of that.

**Comment by cytadela8** [comment]
@fepitre Sorry, I translated my comment.

**Pull request closed without merging**
